#!/bin/sh
#  執行方法   
#
#echo ' Step 1: prepare  ic_launcher.png a_4.7_750x1334_1.png  a_4.7_750x1334_2.png a_4.7_750x1334_3.png a_4.7_750x1334_4.png a_4.7_750x1334_5.png'
#echo ' Step 2: $./myappyesImages.sh'
# 
# Example for use of GNU gettext.
# This file is in the public domain.
#
# Script for cleaning all autogenerated files.
# 處理參數  

DirTarget="target/"

Repleace_ScrrenshotiPadResize(){
  value=1
  Repleace_resize_iPad_each
  value=2
  Repleace_resize_iPad_each
  value=3
  Repleace_resize_iPad_each
  value=4
  Repleace_resize_iPad_each
  value=5
  Repleace_resize_iPad_each

}

Repleace_resize_iPad_each(){
file="ipad"$value".png"
#rm  -rf target
rm  -rf 1.png
rm  -rf 2.png
mkdir $DirTarget
#rm -rf 512x512.png
# curl -o 1.png $4
cp $file 1.png
if [ ${file: -4} == ".jpg" ]
then
  # curl -o 1.jpg $4
  sips -s format jpg  1.jpg  --out 1.png
  rm -rf 1.jpg
else
  if [ ${file: -4} == ".jpeg" ]
  then
   #  curl -o 1.jpg $4
    sips -s format jpg  1.jpg  --out 1.png
    rm -rf 1.jpg
  fi
fi


  filename=$DirTarget"c_5_5_1024x768_"$value".png"
  sips -s format png  1.png -z 768 1024  --out $filename
  filename=$DirTarget"c_5_5_2048x1536_"$value".png"
  sips -s format png  1.png -z 1569 2048  --out $filename
  filename=$DirTarget"c_5_5_2732x2048_"$value".png"
  sips -s format png  1.png -z 2048 2732  --out $filename
}

Repleace_ScrrenshotiPhoneResize(){
  value=1
  Repleace_resize_each
  value=2
  Repleace_resize_each
  value=3
  Repleace_resize_each
  value=4
  Repleace_resize_each
  value=5
  Repleace_resize_each

}

Repleace_resize_each(){
file="a_4.7_750x1334_"$value".png"
rm  -rf 1.png
rm  -rf 2.png
mkdir $DirTarget
#rm -rf 512x512.png
# curl -o 1.png $4
cp $file 1.png
if [ ${file: -4} == ".jpg" ]
then
  # curl -o 1.jpg $4
  sips -s format jpg  1.jpg  --out 1.png
  rm -rf 1.jpg
else
  if [ ${file: -4} == ".jpeg" ]
  then
   #  curl -o 1.jpg $4
    sips -s format jpg  1.jpg  --out 1.png
    rm -rf 1.jpg
  fi
fi


  filename=$DirTarget"b_5_5_1242x2208_"$value".png"
  sips -s format png  1.png -z 2208 1242  --out $filename
  filename=$DirTarget"b_4_7_750x1334_"$value".png"
  sips -s format png  1.png -z 1334 750  --out $filename
  filename=$DirTarget"b_4_0_640x1136_"$value".png"
  sips -s format png  1.png -z 1136 640  --out $filename
  filename=$DirTarget"b_3_5_640x960_"$value".png"
  sips -s format png  1.png -z 960 640  --out $filename
}


Repleace_ScrrenshotIcon(){

file="ic_launcher.png"


rm  -rf 1.png
rm  -rf 2.png
#rm -rf 512x512.png
# curl -o 1.png $4
cp $file 1.png
if [ ${file: -4} == ".jpg" ]
then
  # curl -o 1.jpg $4
  sips -s format jpg  1.jpg  --out 1.png
  rm -rf 1.jpg
else
  if [ ${file: -4} == ".jpeg" ]
  then
   #  curl -o 1.jpg $4
    sips -s format jpg  1.jpg  --out 1.png
    rm -rf 1.jpg
  fi
fi


  
  sips -s format png  1.png -z 1024 1024 --padColor FFFFFF  --out "1.bmp" -s format bmp 
  filename=$DirTarget"icon_1024x1024.jpg"
  sips  -s format jpeg  "1.bmp" -z 1024 1024 --padColor FFFFFF  --out $filename -s format jpeg 


  filename=$DirTarget"icon-20.png"
  sips -s format png  1.png -z 20 20  --out $filename
  filename=$DirTarget"icon-20@2.png"
  sips -s format png  1.png -z 40 40  --out $filename
  filename=$DirTarget"icon-20@3.png"
  sips -s format png  1.png -z 60 60  --out $filename


  filename=$DirTarget"icon-29.png"
  sips -s format png  1.png -z 29 29  --out $filename
  filename=$DirTarget"icon-29@2.png"
  sips -s format png  1.png -z 58 58  --out $filename
  filename=$DirTarget"icon-29@3.png"
  sips -s format png  1.png -z 87 87  --out $filename


  filename=$DirTarget"icon-40.png"
  sips -s format png  1.png -z 40 40  --out $filename
  filename=$DirTarget"icon-40@2.png"
  sips -s format png  1.png -z 80 80  --out $filename
  filename=$DirTarget"icon-40@3.png"
  sips -s format png  1.png -z 120 120  --out $filename


  filename=$DirTarget"icon-60.png"
  sips -s format png  1.png -z 60 60  --out $filename
  filename=$DirTarget"icon-60@2.png"
  sips -s format png  1.png -z 120 120  --out $filename
  filename=$DirTarget"icon-60@3.png"
  sips -s format png  1.png -z 180 180  --out $filename



  filename=$DirTarget"icon-76.png"
  sips -s format png  1.png -z 76 76  --out $filename
  filename=$DirTarget"icon-76@2.png"
  sips -s format png  1.png -z 152 152  --out $filename
  filename=$DirTarget"icon-76@3.png"
  sips -s format png  1.png -z 228 228  --out $filename




  filename=$DirTarget"icon-83.png"
  sips -s format png  1.png -z 83 83  --out $filename
  filename=$DirTarget"icon-83@2.png"
  sips -s format png  1.png -z 167 167  --out $filename
  filename=$DirTarget"icon-83@3.png"
  sips -s format png  1.png -z 249 249  --out $filename





}


main()
{

 rm  -rf target

 Repleace_ScrrenshotiPadResize
 Repleace_ScrrenshotiPhoneResize
 Repleace_ScrrenshotIcon   

rm  -rf 1.png
rm  -rf 2.png
rm  -rf 1.bmp
}




echo '調整圖片大小'
echo ' Automatically generated icon shell script/'
echo ' Step 1: prepare  ic_launcher.png a_4.7_750x1334_1.png  a_4.7_750x1334_2.png a_4.7_750x1334_3.png a_4.7_750x1334_4.png a_4.7_750x1334_5.png'
echo ' Step 2: $./myappyesImages.sh'
main  


